# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b37c99d4379679833b7bc32fcc0f776543cd160abfca5b228aedb57b784061101c08619ea54abdd92e17d66ef7b3c3d8ae1b7fadd6a5021e917b679536db0aee

test:
  secret_key_base: 90f2c30d34cd503c56c8c8e50fff4886652e8aa86a64d0d2ba4a19419ac67769ff6aba5b52c85f782d00b1f6087c58fbbd86d72977227b12d9302544ce4a0035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
